apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: my-elasticsearch
  namespace: elastic-system
spec:
  version: 8.4.3  # Change to the version you want
  nodes:
    - nodeCount: 3
      nodeSpec:
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 1
